name: .NET Core CI/CD

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
        env:
          SA_PASSWORD: "Str0ngP@ssw0rd!"
          ACCEPT_EULA: "Y"

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настройка .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Восстановление зависимостей
      - name: Restore dependencies
        run: dotnet restore

      # 4. Запуск тестов
      - name: Test Build
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=db;User Id=sa;Password=Str0ngP@ssw0rd!;Trusted_Connection=False;TrustServerCertificate=True;"
        run: dotnet test --no-restore --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "danimir422"
          password: "13DhtvzBuhfnm23"

      # 3. Установка Docker-Compose
      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose
      # 4. Сборка и публикация Docker-образа
      - name: Build and push Docker Compose image
        run: |
          docker-compose build
          docker-compose up

